In [1]:
import yfinance as yf
import pandas as pd

# Set the start and end date
start_date = '2021-07-06'
end_date = '2021-10-04'
ticker=['ACC','ADANIPORTS.NS','ADANIENT.NS','ADANIPOWER.NS','AMBUJACEM.NS','APOLLOHOSP.NS','ARVIND.NS','ASIANPAINT.NS','AUROPHARMA.NS',
'BAJFINANCE.NS','BALKRISIND.NS','BANKBARODA.NS','BANKINDIA.NS', 'BERGEPAINT.NS','BHEL.NS','BAJAJFINSV.NS','BOSCHLTD.NS','CADILAHC.NS',  
'CENTURYTEX.NS','CHOLAFIN.NS','CUMMINSIND.NS','DIVISLAB.NS','DLF.NS','ENGINERSIN.NS','EQUITAS.NS','ESCORTS.NS','FEDERALBNK.NS',
'GODREJCP.NS','GRASIM.NS','HAVELLS.NS','HCLTECH.NS','BSOFT.NS','HDFCBANK.NS','HEXAWARE.NS','HINDPETRO.NS', 
'CANBK.NS','HINDZINC.NS','IDEA','IDFCFIRSTB.NS','CASTROLIND.NS','INDIGO.NS','INDUSINDBK.NS','INFY','IOC.NS','DHFL.NS','ITC',       
'JINDALSTEL.NS','EICHERMOT.NS','JSWSTEEL.NS','JUBLFOOD.NS','JUSTDIAL.NS','KOTAKBANK.NS','EXIDEIND.NS','L&TFH.NS','LUPIN.NS',     
'M&M.NS','GLENMARK.NS','MARICO.NS','MCDOWELL-N.NS','MCX.NS','MOTHERSUMI.NS','MRF.NS','MUTHOOTFIN.NS','NATIONALUM.NS','NCC',       
'ICICIPRULI.NS','NESTLEIND.NS','NTPC.NS','ONGC.NS','PAGEIND.NS','INFRATEL','PFC','PIDILITIND.NS','PNB.NS','RAMCOCEM.NS',  
'RAYMOND.NS','RECLTD.NS','RELCAPITAL.NS','RELIANCE.NS','SAIL','SIEMENS.NS','SRF.NS','SRTRANSFIN.NS','STAR','TATAGLOBAL.NS',
'TATAPOWER.NS','TCS','MGL.NS','TECHM.NS','MINDTREE.NS','TORNTPOWER.NS','UBL.NS','UJJIVAN.NS','UNIONBANK.NS','UPL.NS','VEDL',      
'VOLTAS.NS','WIPRO.NS','YESBANK.NS','AMARAJABAT.NS','NIITLTD.NS', 'RELINFRA.NS','APOLLOTYRE.NS','AXISBANK.NS','TITAN.NS',     
'ASHOKLEY.NS','BAJAJ-AUTO.NS','BATAINDIA.NS','BEL.NS','BHARATFORG.NS','BIOCON.NS','BPCL.NS',      
'BRITANNIA.NS','CESC.NS','CIPLA.NS','COALINDIA.NS','DABUR.NS','DISHTV.NS','GAIL.NS','GMRINFRA.NS','HDFC.NS','HEROMOTOCO.NS','CONCOR.NS',    
'HINDALCO.NS','DRREDDY.NS','HINDUNILVR.NS','IBULHSGFIN.NS','IDBI.NS','IGL.NS','MANAPPURAM.NS','MFSL.NS','M&MFIN.NS','MARUTI.NS','OFSS.NS',      
'NMDC.NS','OIL','POWERGRID.NS','RBLBANK.NS','SHREECEM.NS','SUNPHARMA.NS','TATASTEEL.NS','TATAELXSI.NS','TORNTPHARM.NS','TVSMOTOR.NS',  
'ULTRACEMCO.NS','ZEEL.NS','COLPAL.NS','ICICIBANK.NS','LICHSGFIN.NS','SBIN.NS','BHARTIARTL.NS','LT.NS','NBCC.NS','KAJARIACER.NS','PEL.NS',       
'PETRONET.NS','PVR.NS','TATACHEM.NS','TATAMOTORS.NS','TATAMTRDVR.NS','SUNTV.NS']
data=yf.download(ticker, start_date,end_date)
data

df=data['Close']
df

exc=df.to_excel("data.xlsx")
exv=pd.read_excel("data.xlsx",header=None)
exv

[*********************100%***********************]  161 of 161 completed

3 Failed downloads:
- INFRATEL: No data found, symbol may be delisted
- TATAGLOBAL.NS: No data found, symbol may be delisted
- HEXAWARE.NS: No data found for this date range, symbol may be delisted

,0,1,2,3,4,5,6,7,8,9,...,152,153,154,155,156,157,158,159,160,161
0,Date,ACC,ADANIENT.NS,ADANIPORTS.NS,ADANIPOWER.NS,AMARAJABAT.NS,AMBUJACEM.NS,APOLLOHOSP.NS,APOLLOTYRE.NS,ARVIND.NS,...,UBL.NS,UJJIVAN.NS,ULTRACEMCO.NS,UNIONBANK.NS,UPL.NS,VEDL,VOLTAS.NS,WIPRO.NS,YESBANK.NS,ZEEL.NS
1,2021-07-06 00:00:00,48.54,1414.8,712.7,111.9,744.2,351.85,3706.25,229.95,89.25,...,1429.9,197.35,6933.05,37.7,803.3,14.32,1012.6,532.6,13.35,219.45
2,2021-07-07 00:00:00,48.86,1425.65,720.1,109.8,738.35,357.45,3715.6,231.1,88.55,...,1432.45,206.05,6925.1,37.95,816.9,14.58,1005.5,532.15,13.3,219.65
3,2021-07-08 00:00:00,48.3,1425.9,711.7,108.75,738.45,360.75,3671.4,226.9,88.5,...,1420.2,203.4,6901.9,37.05,814.1,14.06,1011.7,531,13.35,216.15
4,2021-07-09 00:00:00,49.26,1431.35,728.5,109.55,739.7,363.6,3725.9,228.2,88.1,...,1431.35,204,6899.55,36.75,814.55,14.85,1015.4,525.8,13.25,216.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,2021-09-27 00:00:00,49.63,1531.25,750.25,97,762.85,418,4565.55,231.85,95.3,...,1555.55,153.2,7622.9,34.6,725.85,15.22,1218.2,653.9,12.9,322.25
61,2021-09-28 00:00:00,49.58,1487.3,738.7,96,753.35,413.1,4411.05,226.4,95.25,...,1564.7,151.9,7588.3,35,716.8,15.21,1208.95,639.6,12.75,309.15
62,2021-09-29 00:00:00,50,1485.65,742,98.3,756.55,406.45,4423.5,224.7,94.7,...,1557.05,152.85,7464.55,36.4,717.15,15.48,1205.2,640.75,12.3,309.9
63,2021-09-30 00:00:00,48.45,1468.1,737.9,97.1,749.8,400.2,4481.6,225.7,94.45,...,1571.5,155.7,7396.1,36.25,707.7,15.28,1218.05,634.1,12.55,303.2
64,2021-10-01 00:00:00,49.31,1458.7,734.95,96.95,766.8,402.25,4459.4,224.25,94.45,...,1577.45,153.15,7483.55,36.45,712.65,15.48,1215.25,636.25,12.85,295.85